language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install -U pytest
script: pytest tests
deploy:
  provider: pypi
  user: gleon99
  password:
    secure: JOjVh9ZNTky+DxhOCOalL/uIw8O0XMpaqV9ZoFpQtVJ84imiLPp04kdfe4D5JOVLev5dAbDQ5X94xdpW2huFEjGZ439g2RvHMMDS74lEHleWTLIhBH4zndouieyq9K/SG9y6iLw8XooXZvee+Dsg/SqptBiauAyekRRHLTTomKkn0PMNaRLj8uQyph18AOXa8wtNHkEu3ZumeSPAXtRYueZMBRis8dImTkLo5CydKR0C5lIPuSHjChGais2xAoDGdult644r1wSprmGZl7sWgpnITTZLlp8KxHzknGvGb1JHeNHqVR5vBaXw37IG+xX5DCpG+FstTiYybk9hGsDDiibvUyT/7M3K9WEXEBD97pstNArFJ2C49x4zBIiOXk/r68C6sQ939WqOOT4ER26/OtjgV97uIjwwaGMRGmrAOuE4Lce+lvqvfmKw29oncgPwAr88/bwxxOFGiwXU5oBpERPQ94EmLpO/jxY+KwdykvbL3zIvfBQliDYadsRFSqcUNITS/XiRcV4bJ8AIGklnLdtRyCmy/EJtX3lO64p9LjcAjvkFQbXhkh7rx2Fxdcsa/gzk1pETTfidDIMxYFAsfzy+MIEhmcGW5uAbrfQ3QNY2+7jF7lLa+3vfh/NjmOVEAVBYNlDdCJGNb0htYFxWl/KKHhNTZapef+V7J3BXovU=
  on:
    tags: true
    repo: Infinidat/infi.dtypes.nqn
